language: swift
os: osx
osx_image: xcode13.2
xcode_project: ./Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj
xcode_scheme: ZcashLightClientSample
xcode_destination: platform=iOS Simulator,OS=15.2,name=iPhone 8
addons:
  homebrew:
    packages:
    - sourcery
    - swiftlint
